// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbcFxAiJy5RP044Mx7q0PUf0B3xCLc7cs',
    appId: '1:654847572786:web:00de8770a3e1d2aacf752b',
    messagingSenderId: '654847572786',
    projectId: 'chatapp-5bd58',
    authDomain: 'chatapp-5bd58.firebaseapp.com',
    storageBucket: 'chatapp-5bd58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAux-e0Z_O1_adEZPAygjRrR82oZxKxDIU',
    appId: '1:654847572786:android:7d02168f8ee9eb17cf752b',
    messagingSenderId: '654847572786',
    projectId: 'chatapp-5bd58',
    storageBucket: 'chatapp-5bd58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiqiZ45QCNNpZZb2hVPGqKPwtauS2SWLw',
    appId: '1:654847572786:ios:03971d7a249abbffcf752b',
    messagingSenderId: '654847572786',
    projectId: 'chatapp-5bd58',
    storageBucket: 'chatapp-5bd58.appspot.com',
    androidClientId: '654847572786-13nq5njrgbtmccnsamdqll0v6r68h451.apps.googleusercontent.com',
    iosClientId: '654847572786-sngdll43arr95lo76f0oisai02puullj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiqiZ45QCNNpZZb2hVPGqKPwtauS2SWLw',
    appId: '1:654847572786:ios:cb4ee7ab46357449cf752b',
    messagingSenderId: '654847572786',
    projectId: 'chatapp-5bd58',
    storageBucket: 'chatapp-5bd58.appspot.com',
    androidClientId: '654847572786-13nq5njrgbtmccnsamdqll0v6r68h451.apps.googleusercontent.com',
    iosClientId: '654847572786-j39tvth22kf8sl1tvjp2fe43aunmhi6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
