// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz-o6gzUD41k4UnYLQWp4p_yI9Oy6DK1g',
    appId: '1:560072703175:web:071efaffd4da2c308892e2',
    messagingSenderId: '560072703175',
    projectId: 'itiapp-58557',
    authDomain: 'itiapp-58557.firebaseapp.com',
    storageBucket: 'itiapp-58557.appspot.com',
    measurementId: 'G-NB1N5CWXTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQOweFBKsopFf3lRy-IWfxDbhJbnqZq5k',
    appId: '1:560072703175:android:882a8433458bdfab8892e2',
    messagingSenderId: '560072703175',
    projectId: 'itiapp-58557',
    storageBucket: 'itiapp-58557.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQWwik_RmIp4GdwfyHFCuoiS9EU5uWUOk',
    appId: '1:560072703175:ios:b3b512944daa09348892e2',
    messagingSenderId: '560072703175',
    projectId: 'itiapp-58557',
    storageBucket: 'itiapp-58557.appspot.com',
    iosClientId: '560072703175-jon0e51f221ejfsj3eefust3igf82a7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQWwik_RmIp4GdwfyHFCuoiS9EU5uWUOk',
    appId: '1:560072703175:ios:b3b512944daa09348892e2',
    messagingSenderId: '560072703175',
    projectId: 'itiapp-58557',
    storageBucket: 'itiapp-58557.appspot.com',
    iosClientId: '560072703175-jon0e51f221ejfsj3eefust3igf82a7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiApp',
  );
}
